---
# Tasks
# =====
- name: "Block"
  notify: "Restart: nscp"
  when: ansible_os_family == "Windows"
  block:

    - name: "Assert vars: nscp"
      ansible.builtin.assert:
        that:
          - nscp_allowed_hosts is defined
          - nscp_cache_allowed_hosts is defined
          - nscp_timeout is defined
          - nscp_nrpe_allow_arguments is defined
          - nscp_nrpe_nasty_characters is defined
          - nscp_nrpe_allowed_hosts is defined
          - nscp_nrpe_use_ssl is defined
          - nscp_nrpe_insecure is defined
          - nscp_nrpe_port is defined
          - nscp_nrpe_performance_data is defined
          - nscp_module_nrpe_server is defined
          - nscp_module_nrpe_simple_cache is defined
          - nscp_module_nrpe_command_client is defined
          - nscp_module_nrpe_check_disk is defined
          - nscp_module_nrpe_check_eventglog is defined
          - nscp_module_nrpe_check_externalscripts is defined
          - nscp_module_nrpe_check_helpers is defined
          - nscp_module_nrpe_check_logfile is defined
          - nscp_module_nrpe_check_nscp is defined
          - nscp_module_nrpe_check_system is defined
          - nscp_module_nrpe_check_tasksched is defined
          - nscp_module_nrpe_check_wmi is defined
          - nscp_module_nrpe_check_net is defined
          - nrpe_win_pdh_total_disk_reads is defined
          - nrpe_win_pdh_total_disk_writes is defined
          - nrpe_win_pdh_thread_context_switches is defined
          - nrpe_win_pdh_memory_page_faults is defined

    - name: "Deploy config: nsclient.ini.j2"
      ansible.builtin.template:
        src: nsclient.ini.j2
        dest: C:\Program Files\NSClient++\nsclient.ini
        backup: true

    - name: "Set Win-Firewall to allow nscp"
      community.windows.win_firewall_rule:
        name: "[ansible-managed] Allow-TCP-NSClient++"
        localport: {{ nscp_nrpe_port }}
        action: allow
        direction: in
        protocol: tcp
        profiles: 
        - domain
        - private
        enabled: yes
        state: present
