---
#
# Tasks
#
- name: "Block"
  ansible.builtin.include_tasks: "{{ tasks }}"
  loop:
    - task_01_install_snmp.yaml
    - task_02_config_sysinfo.yaml
    - task_03_config_firewall.yaml
  loop_control:
    loop_var: tasks
