---
#
# task_03_config_firewall.yaml
#
- name: "Set Win-Firewall to allow SNMP Queries"
  community.windows.win_firewall_rule:
    name: "Allow-UDP-SNMP [ansible-managed]"
    localport: 161
    action: allow
    direction: in
    protocol: udp
    profiles: 
    - domain
    - private
    enabled: yes
    state: present
