---
#
# task_01_install_snmp.yaml
#
- name: "Install SNMP-Service"
  ansible.windows.win_feature:
    name: SNMP-Service
    state: present
    include_sub_features: true
    include_management_tools: true

- name: "Install RSAT-SNMP"
  ansible.windows.win_feature:
    name: RSAT-SNMP
    state: present
    include_sub_features: true
    include_management_tools: true

- name: "Set Win-SNMP-Communities"
  community.windows.win_snmp:
    community_strings:
    - "[SNMP_COMMUNITY]"
    permitted_managers:
    - localhost
    - [IPV4_OF_MONITORING_SYSTEM]
    action: set