---
# Tasks
# =====
#
- name: "Block"
  ansible.builtin.include_tasks: "{{ tasks }}"
  loop:
    - task_01_install_graylog.yaml
    - task_02_configure_graylog.yaml
  loop_control:
    loop_var: tasks
