---
# Tasks
# =====
- name: "Block"
  notify: "Restart: graylog-sidecar"
  when: ansible_os_family == "Windows"
  block:

    - name: "Assert vars: graylog-sidecar"
      ansible.builtin.assert:
        that:
          - graylog_server_url is defined
          - graylog_server_api_token is defined
          - graylog_update_interval is defined
          - graylog_tls_skip_verify is defined
          - graylog_node_id is defined
          - graylog_tls_skip_verify is defined
          - graylog_send_status is defined
          - graylog_log_rotate_max_file_size is defined
          - graylog_log_rotate_keep_files is defined
          - graylog_collector_validation_timeout is defined

    - name: "Deploy config: sidecar.yaml.j2"
      ansible.builtin.template:
        src: sidecar.yaml.j2
        dest: C:\Program Files\Graylog\sidecar\sidecar.yml
        backup: true

    - name: "Deploy config: node-id.j2"
      ansible.builtin.template:
        src: node-id.j2
        dest: C:\Program Files\Graylog\sidecar\node-id
        backup: false