---
# task_01_install_graylog
# =======================
- name: "Block"
  notify: "Restart: graylog-sidecar"
  when: ansible_os_family == "Debian"
  block:

    - name: "Assert vars: graylog-sidecar"
      ansible.builtin.assert:
        that:
          - graylog_server_url is defined
          - graylog_server_api_token is defined
          - graylog_update_interval is defined
          - graylog_tls_skip_verify is defined
          - graylog_node_id is defined
          - graylog_log_rotate_max_file_size is defined
          - graylog_log_rotate_keep_files is defined
          - graylog_collector_validation_timeout is defined

    - name: "Create /tmp directory"
      ansible.builtin.file:
        path: /tmp
        state: directory

    - name: "Copy: graylog-sidecar-repository_1-5_all.deb"
      ansible.builtin.copy:
        src: graylog-sidecar-repository_1-5_all.deb
        dest: /tmp/graylog-sidecar-repository_1-5_all.deb

    - name: "Make package available: graylog-sidecar"
      ansible.builtin.apt:
        deb: /tmp/graylog-sidecar-repository_1-5_all.deb

    - name: "Apt Update"
      ansible.builtin.apt:
        update_cache: yes

    - name: "Install: graylog-sidecar"
      ansible.builtin.apt:
        name: graylog-sidecar