---
# NetBox / Update Serial Numbers
# ==============================
# Update Serial number of single and clustered ASA firewall
#
# 2023-08-26  stefan  init
#

    #
    # Update Serial Number of Single Firewall
    #
    - name: "Firewall-Single: Update Serial Number"
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          name: "{{ fqdn }}"
          serial: "{{ ansible_net_serialnum }}"
        state: present
      ignore_errors: yes

    #
    # Update Serial Number of Clustered Firewall
    #
    - name: "Firewall-Cluster: Update Serial Numbers"
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          name: "{{ item.name }}"
          serial: "{{ ansible_net_stacked_serialnums[idx_stack] }}"
        state: present
      loop: "{{ vchassis_stacked_firewalls }}"
      loop_control:
        index_var: idx_stack
      ignore_errors: yes
